[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
actix-cors = "0.6"
serde_json = "1.0"
octocrab = "0.42"
jsonwebtoken = "9.3.0"
envy = "0.4.0"
dotenv = "0.15.0"
